app/database/models/chat.py
import json
from sqlalchemy import Column, String, BigInteger, Boolean, Time
from app.database.db_setup import Base


class Chat(Base):
    __tablename__ = 'chats'

    # Уникальный идентификатор чата
    chat_id = Column(BigInteger, primary_key=True)
    chat_name = Column(String, nullable=True)  # Название чата
    default_prompt_id = Column(String, nullable=True)  # ID дефолтного промпта
    # Флаг для анализа по расписанию
    schedule_analysis = Column(Boolean, default=False)
    # Время, от которого начинается выборка сообщений (например, 05:00)
    analysis_time = Column(Time, nullable=True)
    send_time = Column(Time, nullable=True)

    def __repr__(self):
        return f"<Chat(chat_id={self.chat_id}, chat_name={self.chat_name}, default_prompt_id={self.default_prompt_id})>"

    def to_dict(self):
        return {
            "chat_id": self.chat_id,
            "chat_name": self.chat_name,
            "default_prompt_id": self.default_prompt_id,
            "schedule_analysis": self.schedule_analysis,
            "analysis_time": self.analysis_time.isoformat() if self.analysis_time else None,
            "send_time": self.send_time.isoformat() if self.send_time else None,
        }

    def to_json(self):
        return json.dumps(self.to_dict())

app/database/models/user.py
from sqlalchemy import Column, String, BigInteger
from app.database.db_setup import Base


class User(Base):
    __tablename__ = 'users'

    user_id = Column(BigInteger, primary_key=True, autoincrement=False)
    username = Column(String)  # Имя пользователя
    login = Column(String)

    def to_dict(self):
        return {
            "user_id": self.user_id,
            "username": self.username,
            "login": self.login
        }

app/routes/account_route.py
import logging
from flask import Blueprint, jsonify, render_template
from flask_jwt_extended import jwt_required, get_jwt_identity


account_bp = Blueprint('account', __name__)


@account_bp.route('/health', methods=['GET'])
def health_check():
    return "OK", 200


@account_bp.route('/account', methods=['GET'])
def account():
    return render_template('account.html')


@account_bp.route('/protected', methods=['GET'])
@jwt_required()
def protected():
    try:
        current_user = get_jwt_identity()
        logging.info(f"Пользователь авторизован: {current_user}")
        return jsonify({"message": "Access granted"}), 200
    except Exception as e:
        logging.error(f"Ошибка авторизации: {str(e)}")
        return jsonify({"error": "Authorization failed"}), 401


@account_bp.route('/get_username', methods=['GET'])
@jwt_required()  # Требуется авторизация с JWT
def get_username():
    current_user = get_jwt_identity()
    return jsonify(current_user), 200

app/templates/account.html
{% extends "base.html" %}


{% block content %}
<div class="container">
    <h2 class="text-center mt-5">Личный кабинет</h2>
    <script src="/static/js/account.js"></script> 
    <!-- Отображение имени пользователя и баланса -->
    <div class="d-flex justify-content-between align-items-center mt-4 mb-4">
        <h4>Имя пользователя: <strong id="username">Загрузка...</strong></h4>
        <!--<h4>Баланс: <strong>1000</strong> (в условных единицах)</h4>-->
    </div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Сервис анализа телеграм чатов</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="/static/favicon.ico">
    <link rel="stylesheet" href="/static/styles/style.css">  
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>

</head>
<body>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/main.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>


    <!-- Фиксированный навбар -->
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #0056b3; z-index: 1050;">
        <div class="container">
            <a class="navbar-brand d-flex align-items-center" href="{{ url_for('account.account') }}" style="color: white;">
                <span class="ms-2">Сервис анализа телеграм чатов</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <button id="logoutButton" class="btn btn-danger" style="display:none;">Выход</button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Основной контейнер -->
    <div class="d-flex" id="content-wrapper" style="padding-top: 70px;">
        <!-- Фиксированный сайдбар -->
        <div class="sidebar bg-light" id="sidebar">
            <ul class="list-group">
                <li class="list-group-item"><a href="/manage_prompts" class="list-group-item-action">Управление промптами</a></li>
                <li class="list-group-item"><a href="/manage_chats" class="list-group-item-action">Управление чатами</a></li>
                <li class="list-group-item"><a href="/manage_users" class="list-group-item-action">Управление пользователями</a></li>
                <li class="list-group-item"><a href="/analysis" class="list-group-item-action">Анализ</a></li>
                <li class="list-group-item"><a href="/analysis_result" class="list-group-item-action">Результаты анализа</a></li>
                <li class="list-group-item"><a href="/logs" class="list-group-item-action">История действий</a></li>
            </ul>
        </div>

        <!-- Основное содержимое -->
        <div class="container" id="main-content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

app/templates/chats.html
{% extends "base.html" %}


{% block content %}

<div class="container mt-5">
    <script src="/static/js/chats.js"></script>
    <h1>Управление чатами</h1>
    <div id="error" class="alert alert-danger" style="display: none;"></div>
    <div>
        <!-- Отдельная кнопка -->
        <button id="updateRouteButton" class="btn btn-primary mb-3">Обновить данные чатов</button>
    </div>
    <div id="content" style="display: none;">
        <table class="table">
            <thead>
                <tr>
                    <th>ID чата</th>
                    <th>Название Чата</th>
                    <th>Промпт по умолчанию</th>
                    <th>Включить Расписание</th>
                    <th>Время Анализа</th>
                    <th>Время Отправки</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody id="chatTable"></tbody>
        </table>
    </div>
</div>



{% endblock %}

app/templates/logs.html
{% extends "base.html" %}

{% block content %}

<script src="/static/js/logs.js"></script>

<div class="container">
    <h1>Логи</h1>
    <div class="mb-3">
        <div class="mb-3">
            <label for="date" class="form-label mt-3">Дата:</label>
            <input type="date" id="date" class="form-control">
        
            <button id="fetch-logs" class="btn btn-primary mt-3">Получить логи</button>
        </div>
        
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Уровень</th>
                <th>Сообщение</th>
                <th>Дата</th>
            </tr>
        </thead>
        <tbody id="logs-table-body">
            <!-- Логи будут добавлены сюда -->
        </tbody>
    </table>
</div>

<div class="d-flex justify-content-between mt-3">
    <button id="prev-page" class="btn btn-secondary" disabled>Предыдущая</button>
    <span id="page-info">Страница 1</span>
    <button id="next-page" class="btn btn-secondary">Следующая</button>
</div>

{% endblock %}

app/templates/manage_chats.html
{% extends "base.html" %}

{% block title %}Manage Chats | Tiacore{% endblock %}

{% block content %}

<div class="container mt-5">
    <script src="/static/js/manage_chats.js"></script> 
    <h1>Управление чатами</h1>
    <div id="error" class="alert alert-danger" style="display: none;"></div>
    <div id="content" style="display: none;">
        <table class="table">
            <thead>
                <tr>
                    <th>ID Чата</th>
                    <th>Название Чата</th>
                    <th>Дефолтный Промпт</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody id="chatTable"></tbody>
        </table>
    </div>
</div>


{% endblock %}

app/templates/status.html
{% extends "base.html" %}


{% block content %}
<script src="/static/js/status.js"></script>
<h1>Статус Задач</h1>
<div id="statusContainer">
    <!-- Здесь будут отображаться статусы задач -->
</div>


{% endblock %}

app/templates/users.html
{% extends "base.html" %}


{% block content %}

<div class="container mt-5">
    <script src="/static/js/users.js"></script>
    <h1>Управление пользователями</h1>
    <div id="error" class="alert alert-danger" style="display: none;"></div>
    <div>
        <!-- Кнопка для обновления пользователей -->
        <button id="updateUsersButton" class="btn btn-primary mb-3">Обновить пользователей</button>
    </div>
    <div id="content" style="display: none;">
        <table class="table">
            <thead>
                <tr>
                    <th>ID пользователя</th>
                    <th>TG account</th>
                    <th>Имя пользователя</th>
                    <th>Действия</th>
                </tr>
            </thead>
            <tbody id="userTable"></tbody>
        </table>
    </div>
</div>

{% endblock %}